Adding listBucket method to S3 client
Dwolla/fs2-aws pull request #6
Opened 2018-12-05 21:12 UTC by kschlorff16

2018-12-05 22:05 UTC, bpholt requested changes

2018-12-05 22:05 UTC, bpholt commented on main/src/test/scala/com/dwolla/fs2aws/s3/S3ClientSpec.scala
> +      when(mockS3.listObjects(any[ListObjectsRequest])).thenAnswer { invo: InvocationOnMock =>
I forgot that SAM inlining is only available in Scala 2.12, but this library is still published for Scala 2.11 as well. We'll need to change this to explicitly create an anonymous subclass of `Answer` in order for it to compile on 2.11.

2018-12-06 23:03 UTC, lochnesh approved these changes

2018-12-06 23:03 UTC, bpholt approved these changes

2018-12-06 23:04 UTC, merged